### ISSUE TITLE
Issue with follow

### ISSUE THREAD

**Issue by HuntBurdick** [avo-hq/stimulus-confetti#2]
I'm trying to prevent the after link with the follow data attribute but either I'm using it wrong or it's not working. I'd like to prevent the change of route after click.

I've tried:
- data-follow-value="false"
- data-follow="false"
- follow="false"

Thanks.

**Comment by adrianthedev** [comment]
It's actually `data-confetti-follow-value="false"`.

My bad for not making the docs clearer.
They are updated now.

Thanks for writing!
